export const MOVIES_LOAD_START = 'MOVIES_LOAD_START';
export const MOVIES_LOAD_SUCCESS = 'MOVIES_LOAD_SUCCESS';
export const MOVIES_LOAD_FAIL = 'MOVIES_LOAD_FAIL';
export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE';